%% Fits Gaus2 function to experimental temperature data using generic coefficients 
% (for use with fittingCoeffSwap)
function hxy = genCoeffGauss2Eq2D(p, P0, th, x, y)

xp = (x - P0(1))*cos(th) + (y-P0(2))*sin(th);
yp = (P0(1) - x)*sin(th) + (y-P0(2))*cos(th);

hxy = p.a1*exp(-((xp-p.b1)/p.c1)^2 - ((yp-p.b2)/p.c2)^2) ...
    + p.a2*exp(-((xp-p.b3)/p.c3)^2 - ((yp-p.b4)/p.c4)^2) ...
    + p.a3*exp(-((xp-p.b5)/p.c5)^2 - ((yp-p.b6)/p.c6)^2) ...
    + p.a4*exp(-((xp-p.b7)/p.c7)^2 - ((yp-p.b8)/p.c8)^2) ...
    + p.d;
